name: Build and Push Multiple GHCR Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        

      - name: Debug list dockerfiles
        run: |
          pwd
          ls ./resources/dockerfiles -la
          git status
          git log -1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build pyspark
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resources/dockerfiles/Dockerfile_pyspark
          push: true
          tags: ghcr.io/jacquemontlab/pyspark:latest
      
      
      - name: Build genomics_tools
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resources/dockerfiles/Dockerfile_genomics_tools
          push: true
          tags: ghcr.io/jacquemontlab/genomics_tools:latest
      
      
      - name: Build duckdb_python
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resources/dockerfiles/Dockerfile_duckdb_python
          push: true
          tags: ghcr.io/jacquemontlab/duckdb_python:latest
      
      
      - name: Build ensembl_vep_113.3
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resources/dockerfiles/Dockerfile_ensembl_vep_113.3
          push: true
          tags: ghcr.io/jacquemontlab/ensembl_vep_113.3:latest
      